node {
   def mvnHome
   stage('Preparation') {

    // get code from github
      git 'https://github.com/ShakedBraimok/simple-java-maven-app.git'

    // maven
      mvnHome = tool 'M3'
   }
   stage('Build') {
      // Run the maven build
         sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"

   }
   stage('Results') {
       // generate jar
      junit '**/target/surefire-reports/TEST-*.xml'
      archive 'target/*.jar'
   }

   stage('Build Image') {
      sh 'cp ./target/my-app-1.0-SNAPSHOT.jar /opt/deployment-files'
      sh 'cd /opt/deployment-files && sudo docker build -t webserver .'
   }


   stage('Upload Image') {
      sh 'docker login --username=shakedbraimok --password=$DOCKER_PASS hub.docker.com'
      sh 'docker tag example-app shakedbraimok/example-app'
      sh 'docker push shakedbraimok/example-app'

   }

}
